#!/usr/bin/env bash

# setup-nginx.sh — nginx installation and configuration for Arch Linux
# Part of webstack-setup
#
# What this script does:
#   1. Installs nginx via pacman
#   2. Detects CPU cores and adjusts worker_processes
#   3. Writes an optimized nginx.conf for local development
#   4. Creates the sites-available / sites-enabled directory structure
#   5. Writes a ready-to-use Laravel virtual host template
#   6. Enables and starts the nginx service
#
# Run: sudo bash setup-nginx.sh
# Idempotent: safe to run multiple times. Creates a backup of nginx.conf before overwriting.

set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────────

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info() { echo -e "${BLUE}[INFO]${NC}  $1"; }
success() { echo -e "${GREEN}[OK]${NC}    $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC}  $1"; }
error() {
    echo -e "${RED}[ERROR]${NC} $1"
    exit 1
}

# ── Root check ────────────────────────────────────────────────────────────────

[[ $EUID -ne 0 ]] && error "Run this script with sudo: sudo bash setup-nginx.sh"

# ── Install nginx ─────────────────────────────────────────────────────────────

info "Installing nginx..."
pacman -S --needed --noconfirm nginx
success "nginx installed."

echo ""

# ── Hardware detection ────────────────────────────────────────────────────────

CPU_CORES=$(nproc)
TOTAL_RAM_MB=$(awk '/MemTotal/ { printf "%d", $2/1024 }' /proc/meminfo)

info "Hardware detected:"
echo "  CPU cores (worker_processes) : ${CPU_CORES}"
echo "  Total RAM                    : ${TOTAL_RAM_MB} MB"
echo ""

# ── Backup original nginx.conf ────────────────────────────────────────────────

NGINX_CONF="/etc/nginx/nginx.conf"

if [[ -f "${NGINX_CONF}" ]]; then
    BACKUP="${NGINX_CONF}.bak.$(date +%Y%m%d%H%M%S)"
    cp "${NGINX_CONF}" "${BACKUP}"
    success "Backup saved: ${BACKUP}"
fi

# ── Write nginx.conf ──────────────────────────────────────────────────────────

info "Writing ${NGINX_CONF}..."

cat >"${NGINX_CONF}" <<EOF
# nginx.conf — generated by webstack-setup/setup-nginx.sh
# Optimized for local development on Arch Linux.

user http;
worker_processes ${CPU_CORES};
pid /run/nginx.pid;

events {
    # Maximum simultaneous connections per worker.
    # Total capacity: worker_processes * worker_connections = ${CPU_CORES} * 1024
    worker_connections 1024;
    multi_accept on;
}

http {
    charset utf-8;

    # Efficient file transfers: sendfile + tcp_nopush send headers and
    # file data in a single packet, reducing round trips.
    sendfile on;
    tcp_nopush on;

    # Disable Nagle's algorithm for low-latency responses.
    tcp_nodelay on;

    # Hide nginx version from error pages and response headers.
    server_tokens off;

    types_hash_max_size 4096;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # ── Logging ───────────────────────────────────────────────────────────────

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log warn;

    # ── Gzip compression ──────────────────────────────────────────────────────

    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_min_length 256;
    gzip_types
        text/plain
        text/css
        text/xml
        text/javascript
        application/json
        application/javascript
        application/xml+rss
        application/atom+xml
        image/svg+xml
        font/woff
        font/woff2;

    # ── Timeouts ──────────────────────────────────────────────────────────────

    keepalive_timeout 65;

    # Max upload size. Should match upload_max_filesize in php.ini.
    client_max_body_size 64M;

    # ── Virtual hosts ─────────────────────────────────────────────────────────

    include /etc/nginx/sites-enabled/*.conf;
}
EOF

success "nginx.conf written."

echo ""

# ── Create sites directories ──────────────────────────────────────────────────

info "Creating sites-available and sites-enabled directories..."

mkdir -p /etc/nginx/sites-available
mkdir -p /etc/nginx/sites-enabled

success "  /etc/nginx/sites-available"
success "  /etc/nginx/sites-enabled"

echo ""

# ── Laravel virtual host template ─────────────────────────────────────────────

TEMPLATE="/etc/nginx/sites-available/laravel.conf.example"
info "Writing Laravel virtual host template to ${TEMPLATE}..."

# Single quotes around 'EOF' prevent variable expansion inside the heredoc.
# All dollar signs in this block are nginx variables, not shell variables.
cat >"${TEMPLATE}" <<'EOF'
# Laravel virtual host template
# ─────────────────────────────────────────────────────────────────────────────
# How to use:
#   1. Copy this file:
#      cp /etc/nginx/sites-available/laravel.conf.example \
#         /etc/nginx/sites-available/<your-project>.conf
#
#   2. Replace every occurrence of <placeholder> with your actual values.
#
#   3. Add the domain to your /etc/hosts:
#      127.0.0.1  <your-domain.local>
#
#   4. Enable the virtual host:
#      ln -s /etc/nginx/sites-available/<your-project>.conf \
#            /etc/nginx/sites-enabled/
#
#   5. Test the configuration and reload:
#      nginx -t && systemctl reload nginx
# ─────────────────────────────────────────────────────────────────────────────

server {
    listen 80;
    server_name <your-domain.local>;

    # Absolute path to the Laravel project's public directory.
    root /path/to/your/project/public;
    index index.php;

    # ── Security headers ──────────────────────────────────────────────────────

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header Referrer-Policy "strict-origin-when-cross-origin";

    # ── Laravel routing ───────────────────────────────────────────────────────

    # Try the requested URI as a file, then as a directory,
    # then fall back to index.php (Laravel's front controller).
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # ── PHP-FPM ───────────────────────────────────────────────────────────────

    location ~ \.php$ {
        # Arch Linux default PHP-FPM socket path.
        fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
        fastcgi_index index.php;

        # $realpath_root resolves symlinks in the root path.
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;

        # Increase timeout for long-running requests (e.g. queued jobs via artisan).
        fastcgi_read_timeout 60;

        # Buffer sizes — increase if you see upstream sent too big header errors.
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }

    # ── Block hidden files ────────────────────────────────────────────────────

    # Deny access to dotfiles (e.g. .env, .git, .htaccess),
    # except for .well-known (used by Let's Encrypt and similar).
    location ~ /\.(?!well-known).* {
        deny all;
    }

    # ── Static assets ─────────────────────────────────────────────────────────

    location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|woff|woff2|ttf|eot|webp|avif)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    # ── Logs ──────────────────────────────────────────────────────────────────

    error_log  /var/log/nginx/<your-project>_error.log;
    access_log /var/log/nginx/<your-project>_access.log;
}
EOF

success "Template written: ${TEMPLATE}"

echo ""

# ── Validate nginx configuration ──────────────────────────────────────────────

info "Validating nginx configuration..."
nginx -t && success "Configuration is valid."

echo ""

# ── Enable and start nginx ────────────────────────────────────────────────────

info "Enabling nginx service..."
systemctl enable --now nginx
success "nginx enabled and started."

# ── Summary ───────────────────────────────────────────────────────────────────

echo ""
echo -e "${GREEN}─────────────────────────────────────────────────────${NC}"
success "nginx setup complete."
echo ""
echo "  nginx.conf      : ${NGINX_CONF}"
echo "  sites-available : /etc/nginx/sites-available/"
echo "  sites-enabled   : /etc/nginx/sites-enabled/"
echo "  Laravel template: ${TEMPLATE}"
echo ""
echo -e "${YELLOW}To activate a virtual host:${NC}"
echo "  1. cp ${TEMPLATE} /etc/nginx/sites-available/<project>.conf"
echo "  2. Edit server_name and root in the new file"
echo "  3. Add the domain to /etc/hosts if needed"
echo "  4. ln -s /etc/nginx/sites-available/<project>.conf /etc/nginx/sites-enabled/"
echo "  5. nginx -t && systemctl reload nginx"
echo -e "${GREEN}─────────────────────────────────────────────────────${NC}"
