#!/usr/bin/env bash

# setup-php.sh — PHP installation and configuration for Arch Linux
# Part of webstack-setup
#
# What this script does:
#   1. Installs PHP, PHP-FPM and required extensions via pacman
#   2. Activates extensions in /etc/php/php.ini and /etc/php/conf.d/
#   3. Configures OPcache based on available RAM
#   4. Adjusts key php.ini settings for local development
#   5. Enables and starts the php-fpm service
#
# Run: sudo bash setup-php.sh
# Idempotent: safe to run multiple times.

set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────────

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info() { echo -e "${BLUE}[INFO]${NC}  $1"; }
success() { echo -e "${GREEN}[OK]${NC}    $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC}  $1"; }
error() {
    echo -e "${RED}[ERROR]${NC} $1"
    exit 1
}

# ── Root check ────────────────────────────────────────────────────────────────

[[ $EUID -ne 0 ]] && error "Run this script with sudo: sudo bash setup-php.sh"

# ── Packages ──────────────────────────────────────────────────────────────────

PACKAGES=(
    php          # Core PHP (includes bcmath, sodium, iconv, opcache and others)
    php-fpm      # FastCGI Process Manager
    php-gd       # GD image processing
    php-intl     # Internationalization
    php-pgsql    # PostgreSQL driver (provides pdo_pgsql and pgsql)
    php-sqlite   # SQLite driver (provides pdo_sqlite and sqlite3)
    php-xsl      # XSL/XSLT support
    php-redis    # Redis extension
    php-igbinary # Binary serializer (dependency of php-redis)
)

info "Installing PHP and extensions via pacman..."
pacman -S --needed --noconfirm "${PACKAGES[@]}"
success "Packages installed."

echo ""

# ── Activate extensions in php.ini ───────────────────────────────────────────

PHP_INI="/etc/php/php.ini"
info "Activating extensions in ${PHP_INI}..."

# These ship commented in Arch's php.ini and need to be explicitly enabled.
EXTENSIONS_PHPINI=(
    "bcmath"
    "gd"
    "iconv"
    "intl"
    "pdo_pgsql"
    "pdo_sqlite"
    "pgsql"
    "sodium"
    "sqlite3"
    "xsl"
)

for ext in "${EXTENSIONS_PHPINI[@]}"; do
    if grep -qE "^;extension=${ext}\s*$" "${PHP_INI}"; then
        sed -i "s/^;extension=${ext}\s*$/extension=${ext}/" "${PHP_INI}"
        success "  extension=${ext}"
    elif grep -qE "^extension=${ext}\s*$" "${PHP_INI}"; then
        warn "  extension=${ext} already active — skipping"
    else
        warn "  extension=${ext} not found in ${PHP_INI} — check manually"
    fi
done

echo ""

# ── Activate extensions in conf.d ─────────────────────────────────────────────

CONFD_DIR="/etc/php/conf.d"
info "Activating extensions in ${CONFD_DIR}/..."

# These extensions ship their own .ini files in conf.d with lines commented out.
CONFD_FILES=(
    "igbinary.ini"
    "redis.ini"
)

for ini_file in "${CONFD_FILES[@]}"; do
    ini_path="${CONFD_DIR}/${ini_file}"

    if [[ ! -f "${ini_path}" ]]; then
        warn "  ${ini_file} not found — skipping"
        continue
    fi

    if grep -qE "^;extension=" "${ini_path}"; then
        sed -i 's/^;extension=/extension=/' "${ini_path}"
        success "  ${ini_file} activated"
    else
        warn "  ${ini_file} already active — skipping"
    fi
done

echo ""

# ── OPcache ───────────────────────────────────────────────────────────────────

info "Configuring OPcache..."

TOTAL_RAM_MB=$(awk '/MemTotal/ { printf "%d", $2/1024 }' /proc/meminfo)

if [[ ${TOTAL_RAM_MB} -ge 16384 ]]; then
    OPCACHE_MEM=256
elif [[ ${TOTAL_RAM_MB} -ge 8192 ]]; then
    OPCACHE_MEM=128
else
    OPCACHE_MEM=64
fi

# Enable the zend extension in php.ini if commented
if grep -qE "^;zend_extension=opcache" "${PHP_INI}"; then
    sed -i 's/^;zend_extension=opcache/zend_extension=opcache/' "${PHP_INI}"
    success "  zend_extension=opcache enabled in ${PHP_INI}"
elif grep -qE "^zend_extension=opcache" "${PHP_INI}"; then
    warn "  zend_extension=opcache already active — skipping"
fi

# Write tuned OPcache settings to conf.d
# validate_timestamps=1 is intentional for local dev (pick up file changes).
# Set to 0 in production for maximum performance.
OPCACHE_CONF="${CONFD_DIR}/opcache.ini"
cat >"${OPCACHE_CONF}" <<EOF
; OPcache configuration — generated by webstack-setup/setup-php.sh
; Tuned for local development.
; In production: set validate_timestamps=0 and revalidate_freq=0.

opcache.enable=1
opcache.enable_cli=0
opcache.memory_consumption=${OPCACHE_MEM}
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=16384
opcache.revalidate_freq=2
opcache.validate_timestamps=1
opcache.fast_shutdown=1
EOF

success "  OPcache configured (${OPCACHE_MEM}MB, validate_timestamps=1)"

echo ""

# ── php.ini adjustments ───────────────────────────────────────────────────────

info "Adjusting php.ini settings..."

# Replaces a commented or active key=value pair.
# Falls back to appending if the key is not found.
set_ini() {
    local key="$1"
    local value="$2"

    if grep -qE "^;?\s*${key}\s*=" "${PHP_INI}"; then
        sed -i "s|^;*\s*${key}\s*=.*|${key} = ${value}|" "${PHP_INI}"
    else
        echo "${key} = ${value}" >>"${PHP_INI}"
    fi

    success "  ${key} = ${value}"
}

set_ini "memory_limit" "256M"
set_ini "upload_max_filesize" "64M"
set_ini "post_max_size" "64M"
set_ini "max_execution_time" "60"
set_ini "default_charset" "UTF-8"
set_ini "date.timezone" "America/Sao_Paulo"

echo ""

# ── PHP-FPM service ───────────────────────────────────────────────────────────

info "Enabling php-fpm service..."
systemctl enable --now php-fpm
success "php-fpm enabled and started."

# ── Summary ───────────────────────────────────────────────────────────────────

echo ""
echo -e "${GREEN}─────────────────────────────────────────────────────${NC}"
success "PHP setup complete."
echo ""
echo "  $(php -v | head -n1)"
echo "  php.ini : ${PHP_INI}"
echo "  conf.d  : ${CONFD_DIR}"
echo ""
echo -e "${YELLOW}Next step: sudo bash setup-fpm.sh${NC}"
echo -e "${GREEN}─────────────────────────────────────────────────────${NC}"
